[package]
name = "lamezip77_macros"
description = "proc macros for lamezip77"
repository = "https://github.com/ArcaneNibble/lamezip77"
license = "0BSD"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"

[dependencies.syn]
version = "2.0"
features = ["full"]
